[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "starlite-saqlalchemy"
version = "0.0.1"
description = "Starlite API and async worker boilerplate"
authors = ["Peter Schutt <peter.github@proton.me>"]
packages = [
    { include = "starlite_saqlalchemy", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.10"
asyncpg = "*"
hiredis = "*"
httpx = "*"
orjson = "*"
pydantic = "*"
redis = "*"
saq = "*"
sentry-sdk = "*"
sqlalchemy = { git = "https://github.com/sqlalchemy/sqlalchemy.git", branch = "main" }
starlite = { git = "https://github.com/starlite-api/starlite.git", branch = "main"}

[tool.poetry.group.linting]
optional = true

[tool.poetry.group.linting.dependencies]
pre-commit = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs-gen-files = "*"
mkdocs-literate-nav = "*"
mkdocs-material = "*"
mkdocs-section-index = "*"
mkdocstrings = {version = "*", extras = ["python"]}
pymdown-extensions = "*"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.coverage.report]
show_missing = true
exclude_lines = [
    'if TYPE_CHECKING:',
    'pragma: no cover',
]

[tool.coverage.run]
omit = [
    "tests/*",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
env_files = ["tests.env"]
testpaths = ["tests/unit"]

[tool.pylint.main]
extension-pkg-whitelist = ["pydantic"]
